import {
  Alert,
  Customer,
  DashboardSummary,
  ServiceSubscription,
  User,
  Website,
} from "@/types/models";

export const users: User[] = [
  { id: "u1", name: "Santi", role: "admin", email: "santi@company.com" },
  { id: "u2", name: "Mawin", role: "admin", email: "mawin@company.com" },
  { id: "u3", name: "Acme Team", role: "admin", email: "it@acme.com" },
];

export const customers: Customer[] = [
  { id: "c1", name: "Acme Corp", contactEmail: "it@acme.com", status: "active" },
  { id: "c2", name: "Blue Ocean", contactEmail: "ops@blueocean.io", status: "active" },
  { id: "c3", name: "Nova Group", contactEmail: "admin@nova.dev", status: "inactive" },
];

export const websites: Website[] = [
  {
    id: "w1",
    customerId: "c1",
    name: "Cliniter Plus",
    frontendUrl: "https://plus.cliniter.com",
    backendUrl: "https://admin.plus.cliniter.com",
    provider: "Cloudflare",
    hostingType: "Cloud",
    status: "online",
    contractStatus: "active",
    contractExpiryDate: "2026-05-10",
    createdAt: "2025-09-08T00:00:00.000Z",
    apiKeyMasked: "sk_live••••a1b2",
  },
  {
    id: "w2",
    customerId: "c2",
    name: "Flowciety",
    frontendUrl: "https://flowciety.net",
    backendUrl: "https://manage.flowciety.net",
    provider: "AWS",
    hostingType: "Hosting",
    status: "offline",
    contractStatus: "active",
    contractExpiryDate: null,
    createdAt: "2025-08-12T00:00:00.000Z",
    apiKeyMasked: "sk_live••••c3d4",
  },
  {
    id: "w3",
    customerId: "c3",
    name: "Horeco",
    frontendUrl: "https://horeco.co.th",
    backendUrl: "https://cms.horeco.co.th",
    provider: "Vercel",
    hostingType: "Cloud",
    status: "online",
    contractStatus: "inactive",
    contractExpiryDate: null,
    createdAt: "2025-07-01T00:00:00.000Z",
    apiKeyMasked: "sk_live••••e5f6",
  },
  {
    id: "w4",
    customerId: "c1",
    name: "Acme Store",
    frontendUrl: "https://store.acme.com",
    backendUrl: "https://admin.store.acme.com",
    provider: "Cloudflare",
    hostingType: "Cloud",
    status: "online",
    contractStatus: "active",
    contractExpiryDate: null,
    createdAt: "2025-06-20T00:00:00.000Z",
    apiKeyMasked: "sk_live••••g7h8",
  },
  {
    id: "w5",
    customerId: "c2",
    name: "Blue Docs",
    frontendUrl: "https://docs.blueocean.io",
    backendUrl: "https://admin.docs.blueocean.io",
    provider: "AWS",
    hostingType: "Hosting",
    status: "online",
    contractStatus: "active",
    contractExpiryDate: null,
    createdAt: "2025-05-15T00:00:00.000Z",
    apiKeyMasked: "sk_live••••i9j0",
  },
  {
    id: "w6",
    customerId: "c1",
    name: "Acme Blog",
    frontendUrl: "https://blog.acme.com",
    backendUrl: "https://wp.acme.com",
    provider: "Cloudflare",
    hostingType: "Hosting",
    status: "online",
    contractStatus: "active",
    contractExpiryDate: null,
    createdAt: "2025-04-10T00:00:00.000Z",
    apiKeyMasked: "sk_live••••k1l2",
  },
  {
    id: "w7",
    customerId: "c2",
    name: "Ocean API",
    frontendUrl: "https://api.blueocean.io",
    backendUrl: "https://console.blueocean.io",
    provider: "AWS",
    hostingType: "Cloud",
    status: "online",
    contractStatus: "active",
    contractExpiryDate: null,
    createdAt: "2025-03-22T00:00:00.000Z",
    apiKeyMasked: "sk_live••••m3n4",
  },
  {
    id: "w8",
    customerId: "c1",
    name: "Acme Portal",
    frontendUrl: "https://portal.acme.com",
    backendUrl: "https://admin.portal.acme.com",
    provider: "Cloudflare",
    hostingType: "Cloud",
    status: "offline",
    contractStatus: "active",
    contractExpiryDate: null,
    createdAt: "2025-02-18T00:00:00.000Z",
    apiKeyMasked: "sk_live••••o5p6",
  },
  {
    id: "w9",
    customerId: "c3",
    name: "Nova App",
    frontendUrl: "https://app.nova.dev",
    backendUrl: "https://admin.app.nova.dev",
    provider: "Vercel",
    hostingType: "Cloud",
    status: "online",
    contractStatus: "active",
    contractExpiryDate: null,
    createdAt: "2025-01-05T00:00:00.000Z",
    apiKeyMasked: "sk_live••••q7r8",
  },
  {
    id: "w10",
    customerId: "c2",
    name: "Blue Marketing",
    frontendUrl: "https://mkt.blueocean.io",
    backendUrl: "https://admin.mkt.blueocean.io",
    provider: "AWS",
    hostingType: "Hosting",
    status: "online",
    contractStatus: "active",
    contractExpiryDate: null,
    createdAt: "2024-12-11T00:00:00.000Z",
    apiKeyMasked: "sk_live••••s9t0",
  },
  {
    id: "w11",
    customerId: "c1",
    name: "Acme HR",
    frontendUrl: "https://hr.acme.com",
    backendUrl: "https://admin.hr.acme.com",
    provider: "Cloudflare",
    hostingType: "Cloud",
    status: "online",
    contractStatus: "active",
    contractExpiryDate: null,
    createdAt: "2024-11-30T00:00:00.000Z",
    apiKeyMasked: "sk_live••••u1v2",
  },
  {
    id: "w12",
    customerId: "c2",
    name: "Blue Support",
    frontendUrl: "https://support.blueocean.io",
    backendUrl: "https://desk.blueocean.io",
    provider: "AWS",
    hostingType: "Hosting",
    status: "online",
    contractStatus: "active",
    contractExpiryDate: null,
    createdAt: "2024-10-14T00:00:00.000Z",
    apiKeyMasked: "sk_live••••w3x4",
  },
  {
    id: "w13",
    customerId: "c1",
    name: "Acme Lab",
    frontendUrl: "https://lab.acme.com",
    backendUrl: "https://admin.lab.acme.com",
    provider: "Cloudflare",
    hostingType: "Cloud",
    status: "online",
    contractStatus: "active",
    contractExpiryDate: null,
    createdAt: "2024-09-01T00:00:00.000Z",
    apiKeyMasked: "sk_live••••y5z6",
  },
  {
    id: "w14",
    customerId: "c3",
    name: "Nova Site",
    frontendUrl: "https://www.nova.dev",
    backendUrl: "https://cms.nova.dev",
    provider: "Vercel",
    hostingType: "Cloud",
    status: "online",
    contractStatus: "active",
    contractExpiryDate: null,
    createdAt: "2024-08-20T00:00:00.000Z",
    apiKeyMasked: "sk_live••••a7b8",
  },
];

export const subscriptions: ServiceSubscription[] = [
  { id: "s1", customerId: "c1", serviceType: "domain", expiryDate: "2026-06-15" },
  { id: "s2", customerId: "c1", serviceType: "ma", expiryDate: "2026-05-03" },
  { id: "s3", customerId: "c1", serviceType: "cloud", expiryDate: "2026-07-20" },
  { id: "s4", customerId: "c2", serviceType: "hosting", expiryDate: "2026-04-20" },
  { id: "s5", customerId: "c2", serviceType: "domain", expiryDate: "2026-04-10" },
];

export const alerts: Alert[] = [
  {
    id: "a1",
    websiteId: "w2",
    message: "ตรวจสุขภาพเว็บไซต์หมดเวลา",
    severity: "high",
    status: "new",
    createdAt: "2026-04-16T08:30:00.000Z",
  },
  {
    id: "a2",
    websiteId: "w3",
    message: "MA ครบกำหนดต่ออายุใน 14 วัน",
    severity: "medium",
    status: "acknowledged",
    createdAt: "2026-04-12T10:45:00.000Z",
  },
  {
    id: "a3",
    websiteId: "w8",
    message: "เว็บไซต์ตอบสนองช้าเกินเกณฑ์ (TTFB)",
    severity: "medium",
    status: "new",
    createdAt: "2026-04-15T14:20:00.000Z",
  },
  {
    id: "a4",
    websiteId: "w4",
    message: "ใบรับรอง SSL จะหมดอายุใน 21 วัน",
    severity: "low",
    status: "new",
    createdAt: "2026-04-14T09:00:00.000Z",
  },
  {
    id: "a5",
    websiteId: "w1",
    message: "สำรองข้อมูลรายวันสำเร็จ",
    severity: "low",
    status: "resolved",
    createdAt: "2026-04-13T22:10:00.000Z",
  },
  {
    id: "a6",
    websiteId: "w7",
    message: "API ตอบกลับ HTTP 5xx ต่อเนื่อง",
    severity: "high",
    status: "acknowledged",
    createdAt: "2026-04-11T16:40:00.000Z",
  },
  {
    id: "a7",
    websiteId: "w10",
    message: "แคมเปญอีเมลแจ้งเตือน: โดเมนใกล้หมดอายุ",
    severity: "low",
    status: "new",
    createdAt: "2026-04-10T11:05:00.000Z",
  },
  {
    id: "a8",
    websiteId: "w5",
    message: "Cron งาน MA รายสัปดาห์ล้มเหลว",
    severity: "medium",
    status: "new",
    createdAt: "2026-04-09T07:55:00.000Z",
  },
  {
    id: "a9",
    websiteId: "w11",
    message: "ตรวจพบลิงก์เสียในหน้าแรก",
    severity: "low",
    status: "resolved",
    createdAt: "2026-04-08T13:30:00.000Z",
  },
  {
    id: "a10",
    websiteId: "w14",
    message: "โควตาดิสก์โฮสติ้งเหลือน้อยกว่า 10%",
    severity: "medium",
    status: "acknowledged",
    createdAt: "2026-04-07T10:15:00.000Z",
  },
];

export const dashboardSummary: DashboardSummary = {
  totalWebsites: websites.length,
  activeWebsites: websites.filter((item) => item.contractStatus === "active").length,
  inactiveWebsites: websites.filter((item) => item.contractStatus === "inactive").length,
  downWebsites: websites.filter((item) => item.status === "offline").length,
};
